export const COLORS = [
    { name: 'cyan', code: '#00FFFF' },
    { name: 'magenta', code: '#FF00FF' },
    { name: 'silver', code: '#C0C0C0' },
    { name: 'gold', code: '#FFD700' },
    { name: 'black', code: '#000000' },
    { name: 'red', code: '#FF0000' },
    { name: 'white', code: '#FFFFFF' },
    { name: 'blue', code: '#0000FF' },
    { name: 'yellow', code: '#FFFF00' },
    { name: 'orange', code: '#FFA500' },
    { name: 'purple', code: '#800080' },
    { name: 'pink', code: '#FFC0CB' },
    { name: 'brown', code: '#A52A2A' },
    { name: 'teal', code: '#008080' },
    { name: 'lime', code: '#00FF00' },
    { name: 'maroon', code: '#800000' },
    { name: 'navy', code: '#000080' },
    { name: 'olive', code: '#808000' },
    { name: 'coral', code: '#FF6F61' },
    { name: 'indigo', code: '#4B0082' },
    { name: 'orchid', code: '#DA70D6' },
    { name: 'turquoise', code: '#40E0D0' },
    { name: 'sky blue', code: '#87CEEB' },
    { name: 'lime green', code: '#32CD32' },
  ];
  